#!/usr/bin/env bash

# Check if the operating system supports it
UNAMEOUT="$(uname -s)"

case "${UNAMEOUT}" in
    Linux*)             MACHINE=linux;;
    Darwin*)            MACHINE=mac;;
    *)                  MACHINE="UNKNOWN"
esac

if [ "$MACHINE" == "UNKNOWN" ]; then
    echo "Unsupported operating system [$(uname -s)]. Mixpost supports macOS, Linux, and Windows (WSL2)." >&2

    exit 1
fi

# Define Docker Compose command prefix
docker compose &> /dev/null
if [ $? == 0 ]; then
    DOCKER_COMPOSE=(docker compose)
else
    DOCKER_COMPOSE=(docker-compose)
fi

ARGS+=(exec -u mixpost)
[ ! -t 0 ] && ARGS+=(-T)
ARGS+=(app "$@")

# Run Docker Compose with the defined arguments
"${DOCKER_COMPOSE[@]}" "${ARGS[@]}"